spring:
      jpa:
         hibernate:
                  ddl-auto: validate
         generate-ddl: true
#         properties:
#                  hibernate:
#                          dialect: org.hibernate.dialect.HSQLDialect
         show-sql: true

      datasource:
                platform: hsqldb
                url: jdbc:hsqldb:mem:test;shutdown=true;sql.syntax_ora=true;hsqldb.tx=mvcc


geoIp:
     database:
              file: ${zeus.config.home}\IPRangeDatabase.dat

zeus:
    config:
          home: C:\Users\Ugo\pollen8