spring:
      jpa:
         hibernate:
                  ddl-auto: validate
         properties:
                  hibernate:
                          dialect: org.hibernate.dialect.MySQL5Dialect
         generate-ddl: false

      datasource:
                platform: hsqldb


geoIp:
     database:
              file: ${zeus.config.home}\IPRangeDatabase.dat

zeus:
    config:
          home: C:\Users\Ugo\pollen8