#spring:
#      jpa:
#         hibernate:
#                  ddl-auto: validate
#         generate-ddl: false
#         properties:
#                  hibernate:
#                          dialect: org.hibernate.dialect.HSQLDialect
#         show-sql: false

#      datasource:
#                platform: hsqldb
#                url: jdbc:hsqldb:mem:test;shutdown=true;sql.syntax_ora=true;hsqldb.tx=mvcc


geoIp:
    database:
          iprange:
                file: ${zeus.config.home}\IPRangeDatabase.dat
          city:
             file: ${zeus.config.home}\GeoLite2-City.mmdb
          isp:
             file: ${zeus.config.home}\GeoIPISP.dat

zeus:
    config:
          home: C:\Users\Ugo\.pollen8