spring:
      profiles:
        active: integrationTest
      jpa:
         hibernate:
                  ddl-auto: validate
         generate-ddl: false
         show-sql: true
         properties:
           hibernate:
             dialect: org.hibernate.dialect.H2Dialect
             synonym: true
             default_schema:
             jdbc:
               batch_size: 100
      datasource:
                platform: hsqldb
                url: jdbc:h2:mem:testdb
                username: sa
                driver-class-name: org.h2.Driver
                hikari:
                  minimum-idle: 2
                  maximum-pool-size: 100